version: "3.5"

services:
  agent1:
    restart: unless-stopped
    build:
      context: .
    network_mode: host
    #volumes:
      #- /media/drive:/media/drive:ro
    environment:
      - METRICS_NET_DEVICE_ETH=wlp0s20f3
      - METRICS_DISK_ROOT=/
      #- METRICS_DISK_EXTERNAL_DD=/media/drive
